package pojos;
// Generated Oct 19, 2018 10:13:44 PM by Hibernate Tools 4.3.1



/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {


     private int idStudent;
     private String firstName;
     private String lastName;

    public Student() {
    }

	
    public Student(int idStudent) {
        this.idStudent = idStudent;
    }
    public Student(int idStudent, String firstName, String lastName) {
       this.idStudent = idStudent;
       this.firstName = firstName;
       this.lastName = lastName;
    }
   
    public int getIdStudent() {
        return this.idStudent;
    }
    
    public void setIdStudent(int idStudent) {
        this.idStudent = idStudent;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }




}


