package pojos;
// Generated Nov 27, 2018 8:13:54 PM by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int userId;
     private String userName;
     private String password;
     private int admin;

    public User() {
    }

    public User(int userId) {
        this.userId = userId;
    }
    public User(int userId, String userName, String password, int admin) {
       this.userId = userId;
       this.userName = userName;
       this.password = password;
       this.admin = admin;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public int getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(int admin) {
        this.admin = admin;
    }




}


