package pojos;
// Generated Nov 27, 2018 8:13:54 PM by Hibernate Tools 4.3.1



/**
 * Vehicle generated by hbm2java
 */
public class Vehicle  implements java.io.Serializable {


     private int vehicleId;
     private String make;
     private String model;
     private Integer year;
     private String vin;
     private String color;
     private String newused;
     private String discription;
     private Boolean sold;

    public Vehicle() {
    }

	
    public Vehicle(int vehicleId) {
        this.vehicleId = vehicleId;
    }
    public Vehicle(int vehicleId, String make, String model, Integer year, String vin, String color, String newused, String discription, Boolean sold) {
       this.vehicleId = vehicleId;
       this.make = make;
       this.model = model;
       this.year = year;
       this.vin = vin;
       this.color = color;
       this.newused = newused;
       this.discription = discription;
       this.sold = sold;
    }
   
    public int getVehicleId() {
        return this.vehicleId;
    }
    
    public void setVehicleId(int vehicleId) {
        this.vehicleId = vehicleId;
    }
    public String getMake() {
        return this.make;
    }
    
    public void setMake(String make) {
        this.make = make;
    }
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }
    public String getVin() {
        return this.vin;
    }
    
    public void setVin(String vin) {
        this.vin = vin;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getNewused() {
        return this.newused;
    }
    
    public void setNewused(String newused) {
        this.newused = newused;
    }
    public String getDiscription() {
        return this.discription;
    }
    
    public void setDiscription(String discription) {
        this.discription = discription;
    }
    public Boolean getSold() {
        return this.sold;
    }
    
    public void setSold(Boolean sold) {
        this.sold = sold;
    }




}


